version: '3.5'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
services:

  ### Redis ##########################################
  redis-master:
    build: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
  redis-slave-1:
    build: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis-slave-1:/data
    ports:
      - "63791:6379"
    networks:
      - backend
    command: redis-server --slaveof redis-master 6379
  redis-slave-2:
    build: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis-slave-2:/data
    ports:
      - "63792:6379"
    networks:
      - backend
    command: redis-server --slaveof redis-master 6379

### Redis Sentinel ##########################################
  redis-sentinel-1:
    build: ./redis-sentinel
    volumes:
      - ${DATA_PATH_HOST}/redis-sentinel-1:/data
    ports:
      - 26379:26379
    networks:
      - backend
  redis-sentinel-2:
    build: ./redis-sentinel
    volumes:
      - ${DATA_PATH_HOST}/redis-sentinel-2:/data
    ports:
      - 26380:26379
    networks:
      - backend

  redis-sentinel-3:
    build: ./redis-sentinel
    volumes:
      - ${DATA_PATH_HOST}/redis-sentinel-3:/data
    ports:
      - 26381:26379
    networks:
      - backend