version: '3.5'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_MASK}
volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
services:

  ### PHP ##############################################
  php:
    container_name: php
    build:
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./php/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ./logs/php:/var/log:rw
      - ./php/supervisord.conf:/etc/supervisord.conf:rw
      - ./php/supervisord.d:/etc/supervisord.d:rw
    expose:
      - "9000"
    restart: always
    networks:
      - backend
  ### NGINX Server #################################
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php
    networks:
      - backend


  ### MySQL ################################################
  mysql:
    container_name: mysql
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql:rw
      - ${MYSQL_LOG_PATH}:/var/log/mysql:rw
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      backend:
        ipv4_address: ${MYSQL_IPV4}

  ### Redis ################################################
  redis:
    container_name: redis
    build: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
